nome = input('Digite seu nome: ')
sobrenome = input('digite seu Sobrenome: ')
idade = input('digite sua idade: ')
altura = input('digite sua altura: ') 
cpf = input('digite seu CPF: ')
endereço = input('digite seu Endereço: ')
telefone = input('digite seu Telefone: ')

print('Nome:', nome)
print('Sobrenome:', sobrenome)
print('Idade:', idade)
print('Altura:', altura)
print('CPF:', cpf)
print('Endereço:', endereço)
print('Telefone:', telefone)